# Generated by Django 3.1.7 on 2022-05-29 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def initiate_basic_account_tiers(apps, schema_editor):
    AccountTier = apps.get_model('accounts', 'AccountTier')
    db_alias = schema_editor.connection.alias
    AccountTier.objects.using(db_alias).bulk_create([
        AccountTier(name='Basic', thumbnail_heights=[200]),
        AccountTier(name='Premium', thumbnail_heights=[200, 400], has_original_link=True),
        AccountTier(name='Enterprise', thumbnail_heights=[200, 400], has_original_link=True, has_expiring_link=True),
    ])


def delete_basic_account_tiers(apps, schema_editor):
    AccountTier = apps.get_model('accounts', 'AccountTier')
    db_alias = schema_editor.connection.alias
    AccountTier.objects.using(db_alias).filter(name="Basic").delete()
    AccountTier.objects.using(db_alias).filter(name="Premium").delete()
    AccountTier.objects.using(db_alias).filter(name="Enterprise").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('thumbnail_heights', models.JSONField()),
                ('has_original_link', models.BooleanField(default=False)),
                ('has_expiring_link', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_subscribers', to='accounts.accounttier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(initiate_basic_account_tiers, delete_basic_account_tiers),
    ]
